### ISSUE TITLE
Status in firebase is "cancelled"

### ISSUE THREAD

**Issue by kirantpatil** [ro31337/libretaxi#633] opened 2017-09-09 12:55 UTC
Hi,

While testing, I booked a car and accepted.

In Firebase it is showing status as "cancelled".

What does it mean ?

Edit: Please find the Firebase screenshot.

![screenshot from 2017-09-09 18 23 24](https://user-images.githubusercontent.com/1178055/30240338-2f29fb6a-955e-11e7-80fd-2b1c813e631e.png)

Thanks.

**Comment by ro31337** [comment] 2017-09-09 18:13
That's not a problem. Currently when you click on "finish", status will be always "cancelled", even if you found a ride. Sometimes it's not easy to implement some functionality for chat bot, comparing to the app, so I intentionally "denormalize" it. I'm closing the issue, let me know if you have any questions.

**Closed by ro31337** 2017-09-09 18:13 UTC

**Comment by kirantpatil** [comment] 2017-09-09 19:00
Please correct me I am wrong. In that case the order should not be created if driver/passenger could not negotiate the price and for which we need cancel option to terminate the conversation and passenger should proceed with next driver to negotiate and Driver should proceed with next Passenger to negotiate to create an order.

**Comment by ro31337** [comment] 2017-09-10 02:28
That's right, the better name for this entity would be "ride request".

We can't have orders, because passengers are supposed to call drivers directly by the phone number they get from LibreTaxi. And we'll never know if ride request has been confirmed or not (and that's good for us at the moment, to be honest - less problems).
